name: CI - Static Analysis
on: [push]
jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Static analysis
        uses: crytic/slither-action@v0.1.1
        with:
          node-version: 14
