name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install yarn
          yarn install
      - name: Run lint check
        run: yarn run lint:check
      - name: Run contract compilation
        run: yarn compile
      - name: Run tests
        run: yarn test
      - name: Run slither
        uses: crytic/slither-action@v0.1.1
        with:
          ignore-compile: true
          node-version: 14
